### PR TITLE
fixed bug

### PR DESCRIPTION
**Pull request by Eliasj42**
Fixed an issue where the check to determine if a non-cuda gpu existed would always fail

### CODE REVIEW

**Comment by sogartar** [comment]
Could you add better description in the commit message?
Can't this change be also submitted to upstream in the IREE repo? Is this a problem with Shark specificaly?

**Comment by Eliasj42** [comment]
> Could you add better description in the commit message? Can't this change be also submitted to upstream in the IREE repo? Is this a problem with Shark specificaly?



> 



> provided

Fixed an issue where the check to determine if a non-cuda gpu existed would always fail

**Comment by Eliasj42** [comment]
> 

Probably, but I would really like this merged into shark as soon as possible, and I don't know if going through iree would cause even more delays

**Comment by sogartar** [comment]
I meant to also submit it there as well as here.

**Comment by Eliasj42** [comment]
> I meant to also submit it there as well as here.

yeah i can create  a PR for iree too

**Pull request closed without merging**
